#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

wmname LG3D &
vmware-user-suid-wrapper &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config normal_border_color '#1f1f1f'
bspc config focused_border_color '#30302f'
bspc config presel_feedback_color '#512da8'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xset s off &
xset -dpms &

#Screens
if [ "$( xrandr | grep "HDMI-1-0" | awk '{ print $2 }' )" = "connected" ];  then
	xrandr --output HDMI-1-0 --mode 1920x1080 --primary --left-of eDP-1  
fi

feh --bg-fill ~/Wallpapers/girl.jpg &
~/.config/polybar/./launch.sh --shapes &
picom --config ~/.config/picom/picom.conf &
# wal -R
# Cargar configuración gtk
# Iniciar mate-settings-daemon para aplicar configuraciones de MATE
mate-settings-daemon &
#abrir keepassxc
keepassxc &
#blueman
# Iniciar Blueman solo como applet en la bandeja del sistema
blueman-applet &
#Steam
flatpak override --user --filesystem=/mnt/nv com.valvesoftware.Steam

